pushes:
  script:
    - /bin/sh ./scripts/discord-notification.sh "$WEBHOOK_URL"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "push"'
      changes: 
        - ./*.json

update:
  image: alpine:latest
  before_script:
    - apk add --no-cache git curl bind-tools jq
  script:
    - /bin/sh ./scripts/ranges.sh
  only:
    - schedules
