pushes:
  script:
    - /bin/sh ./scripts/discord-notification.sh "$WEBHOOK_URL"
  only:
    - pushes

update:
  image: alpine:edge
  before_script:
    - apk add --no-cache git curl bind-tools
  script:
    - /bin/sh ./scripts/ranges.sh $API_TOKEN $CI_PROJECT_ID
  only:
    - schedules
